CREATE TABLE Kindergartens
(
Id int IDENTITY(1,1) PRIMARY KEY,
GroupName VARCHAR(100),
ChildrenCount int,
KindergartenName VARCHAR(100),
Teacher VARCHAR(100),
CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
